FROM python:3.11-slim-buster

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get -y install libpq-dev gcc 
RUN apt-get update && apt-get -y install libpq-dev gcc


WORKDIR /loan_manager_backend

COPY ./requirements.txt .
RUN pip install --upgrade pip && pip install psycopg2 && pip install -r requirements.txt --no-cache-dir

COPY . .