# Generated by Django 4.2.2 on 2023-06-18 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Denied', 'Denied')], max_length=8)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
            ],
        ),
    ]
