# Generated by Django 4.2.2 on 2023-06-18 21:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.address', verbose_name='Addresses')),
            ],
        ),
    ]
