# Generated by Django 4.2.2 on 2023-06-18 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(choices=[('BR', 'Brazil')], max_length=2)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('additional_info', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
